import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-white shadow-md">
      <div className="container mx-auto px-4 py-3">
        <nav className="flex justify-between items-center">
          <ul className="flex space-x-4">
            <li>
              <Link href="/products" className="text-gray-700 hover:text-black">
                Products
              </Link>
            </li>
            <li>
              <Link href="/cart" className="text-gray-700 hover:text-black">
                Cart
              </Link>
            </li>
            <li>
              <Link href="/checkout" className="text-gray-700 hover:text-black">
                Check out
              </Link>
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
